# .streamlit/secrets.toml
sheet_id = "1NA-AXRDoFYPankkYvRYFB56K3OsNm1aeolXISSFw_bI"
[gcp_service_account]
type = "service_account"
project_id = "zilla-470419"
private_key_id = "2c9a6155362ed8c1bbaf58274accc12956ca5390"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDBGRXaOcs2qe4g
qY89IJqKh+PfV81aJH0ExfnGZdf4sxuL+ff7pLfEhOLmViySwamzyx+0jUy9Ucwh
z+nj1WT4I0KepcrVQOdHQ72yu0wxIKMkPEsjfdcGFrSERhMYjWCzJFXEAhs2dND/
ZeigQE2P8YuALWMznbuFfklLux4CF0uCqi0wWK1bbbDV6bxEuNvjxeCCNp49Neqm
f2chaxYs2y/w09yEs8t9pPZIJIk3xYXBCuv/YUfb8qVd5iAEb6TY3ZGj/31iRC3A
Ra5umfWGchjwpPKHZQvG3f0ZJYGTHNGQAQixI9aFnOnkW9ntq3nCQJDJ7Tgh/ycB
6XUAWE7TAgMBAAECggEAOGU/rRsI/z+VBSQQag1uJTx38IBfwM58VtsNToTrFT8W
MgUBCJU8eKBI9nW/keMO0axm56AHBBnyMQPcrwZhdVky+Uu5mBvbEES4EA3EvGpo
S0pytXxowuX5tdITfK25ysg3ZkYpNXfbnGPik38ESCCHGhnnaalNHbla5cvSAVDT
RxC+okqrmDpUCjQGZSw5lXS5CbJ0JFGroa9qTFqc1tzTk2X2yLDYzBBrbTQ7Z2Mi
ij3R8j7yRBge2k7pbTgWzIoLgpG6z9JKUjopkwOy1FX29xwG3u7vou9/963g8fXd
jB1jyfNiq7Z7MQfIF4e2hs4U56MDfZrjlq4mDIJpsQKBgQDsYHbbBfyQKhmPUbWX
V7JGY8STjtNfvQauinRGiSGyIrVSyolW4HtAEtZ0Obpsd0gxvnO9I6youvXS7oD+
ljKamHsVnUYChtzEb11r7T7MWzWo/ZvY1Dt/RmeAbKPhjdKCxdHgkhMrNRzRfDrH
B94ykIzH+XnXYDWas+i7cuE6MQKBgQDRINltJ8EdfrdVtFNF0Yn3vEEeUhTL6JxR
90Me/jQmJ6TOA1QyPbAkXZ94E7qWQOZ7To+p9XXLHH0Nrf+02+zAQPmsHtYHrDkZ
a+r4iKDaKeGcoHdovs7A0ajIv0lefIP+O9ZWCgLI2Dt4ekd1MrkMSOEb14wPNZgt
3UwMa65UQwKBgFj+UIFRla8pSoo89yNNrx71PPNZGJe48SURl4le48LPcnkDLAX7
aivLa9ZCTb+8gP/JdoXFQqIcEaUiiopPPioaMm0G027sG34Rd5jEr5n81Q0UvnI6
JVRby2f8fw7SeGkn1Ua5eGISExGDthVtDuj2pyo68PZ3kHb4OS0pqUZhAoGBAMC0
SmZBKbxqFbpNziYZ7c5wlHjCHhO/prwI4rred2NpSH3lp2IcYgFAnD/jvh3SdA/P
1qZAX2joOXuviF86ALEvrmGikIrFcmAwh3a5P6+IxDK10xKcMJyRFbzWN19v0Zkl
vl3OH76/Mh3UX6BpOwdM6NHlD1S8iBxLPVZ8q0lNAoGAesOgNTFBNgAAq+unwvdF
oO7kT9tUJNz9klZOnsOd7BKZs+AdUKmQzQf8Z8Vs8zw2MD4cdplrBstCuFXsYz80
onsP7tEmTh7XGTtOqVcnFbx/MzhS8J8qP/sgPlnswHmpskLt4F1ONNuqkFu8EAM2
jjZ+hxcxP9S88eWm/rxDmD0=
-----END PRIVATE KEY-----
"""
client_email = "id-1zilla-sheets@zilla-470419.iam.gserviceaccount.com"
client_id = "112146627477852025769"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/id-1zilla-sheets@zilla-470419.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
